services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: nodejs_crud_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: usersdb
      DB_USER: user
      DB_PASS: password
    ports:
      - "3000:3000"

volumes:
  postgres_data:
